language: node_js
node_js:
- 5.4.1
deploy:
  provider: heroku
  api_key:
    secure: pFuoxXCj+jNPbN8Qwz2CeJJi7SHI9bdZMg2GWCGCBSBaHg5S492KNIqIsYNRuwU9T4QhK8Yw9hu7NDmvtCGy65ouXEe7pQhglCAtpDwenSdkjTGjetzHo4qARF612UtGKfH8sH0Hn79DAsrESDC/DHYPNL6Ee49UrG2Vbv5aQLDy4ZiizK948EdnMzx05IpLlTJYC9qVXTsbJN5wuKybl5CY5TKkFnMMnnEDdNP9cmhVB0ST0lN5+MujcjA2zUf4ZyL24XISY3dtCNZfTrzPEvCDXjssBIgGp+fXe/BzBy41bmaF2Yo/dBZ+mtLTlpYRg5d1mhKHM2DDDGIdUfTpTWGxa7vtRDyZwwQPz1O6DdfYYB0yF47rsQKuEHflfFzDTZyFKAOH8t+afm74CFutiYMksW+Ww26PQfU/hYFkn94Rh0oQpPAdp/VbCWHNiejZgNShl3Fiw8gK99vzFZTnM4zo9pmRTkHmaV1idBWRUAKESc3jZPEISOitEzmwHnozpEfC9hSuRxtWS/2FQud1P2qtusPzBNQAytr6Tyiw4lx8RUW8CWSz0N/4Acq7RIoyd5GPQhQ9i/4Ii0aADZMFRcz9fO0Fw9DDHnG0cE0i/ub1OicpA+MWMSnuTL1KCwIodIZ5ojc4N/HfJ3vuI9s5avzgA7d1vErTBL1BB49vKF8=
  app:
    master: young-dusk-9003
